const video=document.querySelector('#camera'),canvas=document.querySelector('#overlay'),ctx=canvas.getContext('2d'),cam=document.querySelector('#cam'),imu=document.querySelector('#imu'),fpsEl=document.querySelector('#fps'),hand=document.querySelector('#hand'),sampleEl=document.querySelector('#sample'),motionEl=document.querySelector('#motion'),latencyEl=document.querySelector('#latency'),start=document.querySelector('#start'),center=document.querySelector('#center'),status=document.querySelector('#status'),scanstate=document.querySelector('#scanstate'),diag=document.querySelector('#diag'),datasetBtn=document.querySelector('#dataset'),antModelEl=document.querySelector('#antmodel');let base=null,yaw=0,pitch=0,roll=0,frames=0,t0=performance.now(),running=false,prev=null,lastSample=0,skin=null,track=null,pose=null,poseBusy=false,poseLast=0,poseMs=0,datasetOn=false,dataset=[],lastCapture=0;const probe=document.createElement('canvas'),pctx=probe.getContext('2d',{willReadFrequently:true});probe.width=96;probe.height=72;const BONES=[[0,1],[1,2],[2,3],[3,4],[0,5],[5,6],[6,7],[7,8],[5,9],[9,10],[10,11],[11,12],[9,13],[13,14],[14,15],[15,16],[13,17],[17,18],[18,19],[19,20],[0,17]];
let handsEngine=null,poseHandedness='UNKNOWN';
async function initHandPose(){
 if(!window.Hands)throw Error('runtime Hand Pose não carregou');
 handsEngine=new Hands({locateFile:f=>'https://cdn.jsdelivr.net/npm/@mediapipe/hands/'+f});
 handsEngine.setOptions({maxNumHands:1,modelComplexity:1,minDetectionConfidence:.65,minTrackingConfidence:.65});
 handsEngine.onResults(r=>{pose=(r.multiHandLandmarks&&r.multiHandLandmarks[0])||null;poseHandedness=(r.multiHandedness&&r.multiHandedness[0]&&r.multiHandedness[0].label)||'UNKNOWN';poseBusy=false;
  if(pose){hand.textContent='HAND 21';sampleEl.textContent='landmarks: 21/21';motionEl.textContent='confiança: TRACK';scanstate.textContent='SCANNER: 21/21 TRACKING';diag.textContent='diagnóstico: landmarks anatômicos ativos';}
  else{sampleEl.textContent='landmarks: 0/21';motionEl.textContent='confiança: LOST';scanstate.textContent='SCANNER: PROCURANDO MÃO';diag.textContent='diagnóstico: pose não encontrada';}
 });
}
function drawPose(lm){if(!lm||lm.length!==21)return;const W=innerWidth,H=innerHeight;ctx.save();ctx.strokeStyle='#78ffb2';ctx.fillStyle='#78ffb2';ctx.lineWidth=2;ctx.globalAlpha=.95;
 for(const [a,b] of BONES){ctx.beginPath();ctx.moveTo(lm[a].x*W,lm[a].y*H);ctx.lineTo(lm[b].x*W,lm[b].y*H);ctx.stroke()}
 for(let i=0;i<21;i++){ctx.beginPath();ctx.arc(lm[i].x*W,lm[i].y*H,i===0?5:3,0,Math.PI*2);ctx.fill()}ctx.restore()}
function handCrop(lm){let minX=1,minY=1,maxX=0,maxY=0;for(const p of lm){minX=Math.min(minX,p.x);minY=Math.min(minY,p.y);maxX=Math.max(maxX,p.x);maxY=Math.max(maxY,p.y)}const pad=.12,w=maxX-minX,h=maxY-minY;minX=Math.max(0,minX-w*pad);maxX=Math.min(1,maxX+w*pad);minY=Math.max(0,minY-h*pad);maxY=Math.min(1,maxY+h*pad);return{x:minX,y:minY,w:maxX-minX,h:maxY-minY}}
function captureSample(now){if(!datasetOn||!pose||pose.length!==21||now-lastCapture<350)return;const crop=handCrop(pose),vw=video.videoWidth,vh=video.videoHeight;if(!vw||!vh||crop.w<.05||crop.h<.05)return;lastCapture=now;const c=document.createElement('canvas'),cw=224,ch=224;c.width=cw;c.height=ch;const cc=c.getContext('2d');cc.drawImage(video,crop.x*vw,crop.y*vh,crop.w*vw,crop.h*vh,0,0,cw,ch);const image=c.toDataURL('image/jpeg',.72),landmarks=pose.map(p=>({x:+((p.x-crop.x)/crop.w).toFixed(6),y:+((p.y-crop.y)/crop.h).toFixed(6),z:+(p.z||0).toFixed(6)}));dataset.push({id:'ant-'+Date.now()+'-'+dataset.length,t:Date.now(),source:{w:vw,h:vh},handedness:poseHandedness,crop:{x:+crop.x.toFixed(6),y:+crop.y.toFixed(6),w:+crop.w.toFixed(6),h:+crop.h.toFixed(6)},image:{mime:'image/jpeg',w:cw,h:ch,data:image},landmarks});datasetBtn.textContent='DATASET: '+dataset.length;if(dataset.length>=300){datasetOn=false;datasetBtn.textContent='DATASET: 300';status.textContent='Dataset cheio (300 amostras). Exporte antes de continuar.'}}
function exportDataset(){const blob=new Blob([JSON.stringify({format:'ANT-HAND-21',version:2,containsImages:true,imageEncoding:'data-url/jpeg',count:dataset.length,samples:dataset},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ant-hand-dataset-v2-'+Date.now()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function poseProbe(now){if(!running||!handsEngine||poseBusy||video.readyState<2||now-poseLast<50)return;poseBusy=true;poseLast=now;const t=performance.now();try{await handsEngine.send({image:video});poseMs=Math.round(performance.now()-t);latencyEl.textContent='pose: '+poseMs+'ms'}catch(e){poseBusy=false;scanstate.textContent='SCANNER: FALHA POSE';diag.textContent='diagnóstico: '+e.message}}
const rad=x=>(x||0)*Math.PI/180;function resize(){const d=Math.min(devicePixelRatio||1,2);canvas.width=innerWidth*d;canvas.height=innerHeight*d;canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';ctx.setTransform(d,0,0,d,0,0)}addEventListener('resize',resize);resize();function orient(e){const v={a:rad(e.alpha),b:rad(e.beta),g:rad(e.gamma)};if(!base)base=v;yaw=v.a-base.a;pitch=v.b-base.b;roll=v.g-base.g;imu.textContent='IMU LIVE'}async function enableMotion(){if(typeof DeviceOrientationEvent?.requestPermission==='function'){const p=await DeviceOrientationEvent.requestPermission();if(p!=='granted')throw Error('IMU negada')}addEventListener('deviceorientation',orient,true);imu.textContent='IMU WAIT'}async function enableCamera(){const stream=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720},frameRate:{ideal:30,max:60}}});video.srcObject=stream;await video.play();cam.textContent='CAM LIVE'}function handMask(data,w,h){let sx=0,sy=0,n=0,minX=w,maxX=0,minY=h,maxY=0;for(let y=0;y<h;y++)for(let x=0;x<w;x++){let i=(y*w+x)*4,r=data[i],g=data[i+1],b=data[i+2],mx=Math.max(r,g,b),mn=Math.min(r,g,b);let ok=r>70&&g>35&&b>20&&(mx-mn)>18&&r>g&&r>b&&Math.abs(r-g)>8;if(ok){sx+=x;sy+=y;n++;minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y)}}return n>180?{x:sx/n,y:sy/n,n,minX,maxX,minY,maxY,w,h}:null}
function drawHand(m){if(!m)return;const vw=innerWidth,vh=innerHeight,videoRatio=video.videoWidth/video.videoHeight,viewRatio=vw/vh;let sw,sh,ox=0,oy=0;if(videoRatio>viewRatio){sh=vh;sw=vh*videoRatio;ox=(vw-sw)/2}else{sw=vw;sh=vw/videoRatio;oy=(vh-sh)/2}const X=x=>ox+(x/m.w)*sw,Y=y=>oy+(y/m.h)*sh,cx=X(m.x),cy=Y(m.y),bw=Math.max(55,X(m.maxX)-X(m.minX)),bh=Math.max(90,Y(m.maxY)-Y(m.minY));ctx.save();ctx.strokeStyle='#78ffb2';ctx.fillStyle='#78ffb2';ctx.lineWidth=2;ctx.globalAlpha=.9;ctx.strokeRect(cx-bw*.45,cy-bh*.5,bw*.9,bh);const wrist={x:cx,y:cy+bh*.38},palm={x:cx,y:cy+bh*.08};let tips=[[-.38,-.18],[-.28,-.48],[-.10,-.58],[.10,-.58],[.29,-.47],[.40,-.25]].map(([x,y])=>({x:cx+x*bw,y:cy+y*bh}));for(const t of tips){ctx.beginPath();ctx.moveTo(wrist.x,wrist.y);ctx.lineTo(palm.x,palm.y);ctx.lineTo(t.x,t.y);ctx.stroke();ctx.beginPath();ctx.arc(t.x,t.y,4,0,Math.PI*2);ctx.fill()}ctx.beginPath();ctx.arc(wrist.x,wrist.y,5,0,Math.PI*2);ctx.fill();ctx.restore()}
function visionProbe(now){if(!running||video.readyState<2||now-lastSample<100)return;const ts=performance.now();pctx.drawImage(video,0,0,96,72);const image=pctx.getImageData(0,0,96,72),data=image.data;let lum=0,diff=0,n=0;const cur=new Uint8Array(96*72);for(let i=0,j=0;i<data.length;i+=4,j++){const y=(data[i]*77+data[i+1]*150+data[i+2]*29)>>8;cur[j]=y;lum+=y;if(prev)diff+=Math.abs(y-prev[j]);n++}prev=cur;const avg=Math.round(lum/n),movement=prev?Math.round(diff/n):0;sampleEl.textContent='luz: '+avg;motionEl.textContent='movimento: '+movement;latencyEl.textContent='latência: '+Math.round(performance.now()-ts)+'ms';skin=handMask(data,96,72);
if(skin){if(!pose){scanstate.textContent='SCANNER: ROI VALIDADA';diag.textContent='diagnóstico: ROI auxiliar ativa • aguardando Hand Pose';}
 const a=.22;
 if(!track) track={...skin};
 else { for(const k of ['x','y','minX','maxX','minY','maxY']) track[k]=track[k]*(1-a)+skin[k]*a; track.n=skin.n; track.w=skin.w; track.h=skin.h; }
 if(!pose)hand.textContent='ROI ONLY';
}else{track=null;if(!pose){hand.textContent='HAND LOST';scanstate.textContent='SCANNER: PROCURANDO MÃO';diag.textContent='diagnóstico: nenhuma ROI confiável'}}
lastSample=now}function draw(now){ctx.clearRect(0,0,innerWidth,innerHeight);const cx=innerWidth/2+Math.sin(yaw)*34,cy=innerHeight/2+Math.sin(pitch)*26;ctx.save();ctx.translate(cx,cy);ctx.rotate(-roll*.22);ctx.strokeStyle='#9cecff';ctx.lineWidth=1;ctx.globalAlpha=.8;ctx.beginPath();ctx.arc(0,0,18,0,Math.PI*2);ctx.moveTo(-28,0);ctx.lineTo(28,0);ctx.moveTo(0,-28);ctx.lineTo(0,28);ctx.stroke();ctx.restore();visionProbe(now);poseProbe(now);captureSample(now);drawPose(pose);frames++;if(now-t0>=500){fpsEl.textContent=Math.round(frames*1000/(now-t0))+' FPS';frames=0;t0=now}requestAnimationFrame(draw)}requestAnimationFrame(draw);start.addEventListener('click',async()=>{if(running)return;start.disabled=true;status.textContent='Solicitando sensores…';try{await enableMotion();await enableCamera();scanstate.textContent='SCANNER: CARREGANDO HAND POSE';diag.textContent='diagnóstico: inicializando modelo local';await initHandPose();running=true;start.hidden=true;center.hidden=false;datasetBtn.hidden=false;status.textContent='Teacher ativo • ANT v0.1 em preparação para benchmark local.';if(antModelEl)antModelEl.textContent='ANT v0.1: AWAIT MODEL'}catch(e){scanstate.textContent='SCANNER: FALHA';diag.textContent='diagnóstico: '+e.message;status.textContent='Falha: '+e.message;start.disabled=false}});center.addEventListener('click',()=>base=null);
datasetBtn.addEventListener('click',()=>{if(!datasetOn){datasetOn=true;dataset=[];lastCapture=0;datasetBtn.textContent='DATASET: 0';status.textContent='ANT DATASET LAB v2 • coletando recorte da mão + 21 landmarks localmente.'}else{datasetOn=false;datasetBtn.textContent='DATASET: OFF';status.textContent='Dataset pausado • '+dataset.length+' amostras coletadas. Toque e segure DATASET para exportar.'}});
let holdTimer=null;datasetBtn.addEventListener('touchstart',()=>{holdTimer=setTimeout(()=>{if(dataset.length)exportDataset()},900)},{passive:true});datasetBtn.addEventListener('touchend',()=>clearTimeout(holdTimer),{passive:true});
